title: "Marco Badran"
theme: minima

# Replace with your actual GitHub Pages URL
url: "https://marco-badran.github.io/marco-badran/"
baseurl: "/marco-badran/"  # Leave empty if deploying to root

# Plugins
plugins:
  - jekyll-feed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

