# _config.yml

title: "Marco Badran"
theme: minima # Correct theme

url: "https://yourusername.github.io" # Replace with your GitHub Pages URL

plugins:
  - jekyll-feed

# Markdown
markdown: kramdown
kramdown:
  input: GFM