title: "Marco Badran"
theme: minima

# Replace with your actual GitHub Pages URL
url: "https://yourusername.github.io"
baseurl: ""  # Leave empty if deploying to root

# Plugins
plugins:
  - jekyll-feed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

