# _config.yml

title: "My Jekyll Minimal Site"
description: "A simple Jekyll site with a right-aligned image"
author: "Your Name"
email: "you@example.com"
baseurl: "" # leave blank for root
url: "https://yourusername.github.io" # replace with your GitHub Pages URL

theme: minima # Use the 'minima' theme
plugins:
  - jekyll-feed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Exclude files from the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Build settings
permalink: /:year/:month/:day/:title/
