# _config.yml

title: "Marco Badran"
description: "Marco Badran's personal webpage"
author: "Marco Badran"
theme: minima # Correct theme

url: "https://yourusername.github.io" # Replace with your GitHub Pages URL

plugins:
  - jekyll-feed

# Markdown
markdown: kramdown
kramdown:
  input: GFM
